DROP DATABASE IF EXISTS mvc;
CREATE DATABASE mvc;

USE mvc;
DROP TABLE IF EXISTS user;
CREATE TABLE user (
	u_id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
	u_user CHAR(100) NOT NULL UNIQUE,
	u_password CHAR(100) NOT NULL
);

DROP TABLE IF EXISTS cms;
CREATE TABLE cms (
	c_id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
	c_query VARCHAR(255) NOT NULL DEFAULT '',
	c_meta TEXT NOT NULL DEFAULT '',
	c_title VARCHAR(255) NOT NULL DEFAULT '',
	c_subject VARCHAR(255) NOT NULL DEFAULT '',
	c_content TEXT NOT NULL DEFAULT '',
	c_posted VARCHAR(255) NOT NULL DEFAULT 'NOW()',
	c_u_id INT NOT NULL,
	CONSTRAINT FOREIGN KEY (c_u_id) REFERENCES user(u_id)
);
# 'u_user' is username 'u_password' is password.
INSERT INTO user (u_user,u_password) VALUES('admin',SHA1('admin'));