DROP TABLE IF EXISTS user;
CREATE TABLE user (
	u_id INT PRIMARY KEY UNIQUE NOT NULL,
	c_user CHAR(100) NOT NULL
);

DROP TABLE IF EXISTS cms;
CREATE TABLE cms (
	c_id INT PRIMARY KEY UNIQUE NOT NULL,
	c_title VARCHAR(255) NOT NULL DEFAULT '',
	c_subject VARCHAR(255) NOT NULL DEFAULT '',
	c_content TEXT NOT NULL DEFAULT '',
	c_posted VARCHAR(255) NOT NULL DEFAULT 'NOW()',
	c_u_id INT NOT NULL
);